"use strict";

function generateUUID() {
    return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, c => {
        let r = Math.random() * 16 | 0;
        let v = c == 'x' ? r : (r & 0x3 | 0x8);
        return v.toString(16);
    });
}


class ProposalException{
    constructor(errorMessage){
        this.errorMessage = errorMessage;
    }
}

class Proposal{
    constructor(userid, username, title, content){
        this._id = generateUUID();
        this.userid = userid;
        this.username = username;
        this.title = title;
        this.content = content;
        this._likes = 0;
        this._dislikes = 0;
    }

    //setters 

    set id(value){
        throw new ProposalException("Proposals ids are autogenerated");
    }

    set userid(value){
        if(typeof value !== 'string' || value === ''){
            throw new ProposalException("User id cannot be empty or not a string");
        }
        this._userid = value;
    }

    set username(value){
        if(typeof value !== 'string' || value === ''){
            throw new ProposalException("Username cannot be empty or not a string");
        }
        this._username = value;
    }

    set title(value){
        if(typeof value !== 'string' || value === ''){
            throw new ProposalException("Proposal title cannot be empty or not a string");
        }
        this._title = value;
    }

    set content(value){
        if(typeof value !== 'string' || value === ''){
            throw new ProposalException("Proposal content cannot be empty or not a string");
        }
        this._content = value;
    }

    set likes(value){
        if( value > 0 ){
            this._likes = value;
        }else{
            throw new ProposalException("Number of likes cannot be negative");
        }
    }

    set dislikes(value){
        if (value > 0){
            this._dislikes = value;
        }else{
            throw new ProposalException("Number of dislikes cannot be negative");
        }

    }

    //getters
    get id(){
        return this._id;
    }

    get userid(){
        return this._userid;
    }

    get username(){
        return this._username;
    }

    get title(){
        return this._title;
    }

    get content(){
        return this._content;
    }
}

module.exports = Proposal;